---
# ディレクトリ設定
local_srcs_dir: "{{ lookup('env', 'LOCAL_SRCS_DIR') | default('../app/srcs', true) }}"
srcs_dir: "{{ ansible_env.HOME }}/srcs"
data_dir: "{{ ansible_env.HOME }}/data"

# DDNS設定（環境変数から取得）
dynu_hostname: "{{ lookup('env', 'DYNU_HOSTNAME') }}"
dynu_password: "{{ lookup('env', 'DYNU_PASSWORD') }}"

# Let's Encrypt設定（環境変数から取得）
letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"
