---
# グローバル ディレクトリ設定
local_srcs_dir: "{{ lookup('env', 'LOCAL_SRCS_DIR') | default('../app/srcs/', true) }}"
srcs_dir: "{{ ansible_env.HOME }}/srcs"
data_dir: "{{ ansible_env.HOME }}/data"

# 必要なパッケージ
required_packages:
  - ca-certificates
  - curl
  - certbot

# グローバル設定（複数のロールで参照）
dynu_hostname: "{{ lookup('env', 'DYNU_HOSTNAME') }}"
dynu_password: "{{ lookup('env', 'DYNU_PASSWORD') }}"
letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"
