---
# DDNS (Dynamic DNS) の設定と更新
- name: Configure Dynu updates
  when: dynu_password != '' and dynu_hostname != ''
  block:
    - name: Update Dynu IP address
      uri:
        url: "https://api.dynu.com/nic/update?hostname={{ dynu_hostname }}&password={{ dynu_password }}&myip={{ instance_public_ip }}"
      delegate_to: localhost
      no_log: true

    - name: Create DDNS script directory
      file:
        path: "{{ ansible_env.HOME }}/bin"
        state: directory
        mode: '0755'

    - name: Create DDNS log directory
      file:
        path: "{{ ansible_env.HOME }}/logs"
        state: directory
        mode: '0755'

    - name: Create DDNS update script
      template:
        src: ../templates/ddns_update.sh.j2
        dest: "{{ ansible_env.HOME }}/bin/ddns_update.sh"
        mode: '0700'

    - name: Setup cron job to update Dynu
      cron:
        name: "Update Dynu IP"
        day: "1,15"
        hour: "3"
        minute: "0"
        job: "{{ ansible_env.HOME }}/bin/ddns_update.sh >> {{ ansible_env.HOME }}/logs/ddns-update.log 2>&1"
