---
# Docker Composeでアプリケーションを起動
- name: Start application containers
  ansible.builtin.command: docker compose -f {{ srcs_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ srcs_dir }}"
  changed_when: true
