---
# 必要なパッケージのインストール
- name: Update apt cache and install necessary packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - certbot
      - dnsutils
    update_cache: true
