---
# アプリケーションファイルとディレクトリの準備
- name: Copy srcs to server
  ansible.builtin.copy:
    src: "{{ local_srcs_dir }}/"
    dest: "{{ srcs_dir }}/"
    mode: "u=rwX,g=,o="

# ドメイン名が設定されていない場合は、EC2のパブリックIPを設定する
- name: Set DOMAIN_NAME in .env
  ansible.builtin.lineinfile:
    path: "{{ srcs_dir }}/.env"
    regexp: '^DOMAIN_NAME='
    line: "DOMAIN_NAME={{ dynu_hostname if dynu_hostname else instance_public_ip }}"
    create: true
    mode: "0600"

- name: Set WP_URL in .env
  ansible.builtin.lineinfile:
    path: "{{ srcs_dir }}/.env"
    regexp: '^WP_URL='
    line: "WP_URL=https://{{ dynu_hostname if dynu_hostname else instance_public_ip }}"
    create: true
    mode: "0600"

- name: Create volume directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ data_dir }}/nginx/logs"
    - "{{ data_dir }}/wordpress/data"
    - "{{ data_dir }}/wordpress/logs"
    - "{{ data_dir }}/mariadb/data"
    - "{{ data_dir }}/mariadb/logs"
