---
- name: Deploy WordPress
  hosts: wordpress
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install required packages
      ansible.builtin.import_tasks: tasks/packages.yml
      tags: packages
      become: true

    - name: Configure DDNS
      ansible.builtin.import_tasks: tasks/ddns.yml
      tags: ddns

    - name: Install and configure Docker
      ansible.builtin.import_tasks: tasks/docker.yml
      tags: docker
      become: true

    - name: Prepare application files and directories
      ansible.builtin.import_tasks: tasks/prepare_app.yml
      tags: prepare

    - name: Configure SSL certificates
      ansible.builtin.import_tasks: tasks/ssl.yml
      tags: ssl
      become: true

    - name: Deploy application
      ansible.builtin.import_tasks: tasks/deploy.yml
      tags: deploy
      become: true
