---
- name: Deploy WordPress
  hosts: wordpress
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Install required packages
      ansible.builtin.import_tasks: tasks/packages.yml
      tags: packages
      become: true

  roles:
    - role: ddns
      tags: ddns

    - role: docker
      tags: docker
      become: true

    - role: ssl
      tags: ssl
      become: true

  tasks:
    - name: Prepare application files and directories
      ansible.builtin.import_tasks: tasks/prepare_app.yml
      tags: prepare

    - name: Deploy application
      ansible.builtin.import_tasks: tasks/deploy.yml
      tags: deploy
      become: true
