---
- hosts: wordpress
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - role: ddns
      tags: ddns

    - role: docker
      tags: docker

  tasks:
    - name: Install required packages
      import_tasks: tasks/packages.yml
      tags: packages

    - name: Prepare application files and directories
      import_tasks: tasks/prepare_app.yml
      tags: prepare

    - role: certbot
      tags: ssl

    - name: Deploy application
      import_tasks: tasks/deploy.yml
      tags: deploy
