name: Ansible Lint

on:
  pull_request:
    branches:
      - master
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r ansible/requirements.txt
          ansible-galaxy collection install -r ansible/requirements.yml
      - name: Syntax check
        run: ansible-playbook --syntax-check ansible/main.yml -i wordpress,
      - name: Lint
        run: ansible-lint ansible/main.yml
